### ISSUE TITLE
Example in README indented incorrectly

### ISSUE THREAD

**Issue by quintesse** [jbangdev/jbang-action#1]
It's a little hard to read this way becuase the indenting is not correct. I _think_ this is the correct one:

```
on: [push]

jobs:
  jbang:
    runs-on: ubuntu-latest
    name: A job to run jbang
    steps:
    - name: checkout
      uses: actions/checkout@v1
    - uses: actions/cache@v1
      with:
        path: /root/.jbang
        key: ${{ runner.os }}-jbang-${{ hashFiles('*.java') }}
        restore-keys: |
          ${{ runner.os }}-jbang-
    - name: jbang
      uses: maxandersen/jbang-action@v0.16.1
      with:
        script: createissue.java
        args: "my world"
      env:
        JBANG_REPO: /root/.jbang/repository
        GITHUB_TOKEN: ${{ secrets.ISSUE_GITHUB_TOKEN }}
```

You probably should stop using TABs in files that indent-sensitive ;-)
