### ISSUE TITLE
URL Source protection introduced in 0.28.0 breaks Github Action

### ISSUE THREAD

**Issue by gastaldi** [jbangdev/jbang-action#4]
Having the following GH Action step:

```yaml
      - name: Index Catalog
        uses: jbangdev/jbang-action@v0.28.0
        with:
          script: https://github.com/quarkusio/quarkus-registry-descriptor/blob/master/index.java
          args: --trust=https://github.com/quarkusio/quarkus-registry-descriptor/ . ./app/registry.json
```

Gives the following output: 

```
Run jbangdev/jbang-action@v0.28.0
/usr/bin/docker run --name d33d5e89bf3b5445b3a1f5add313179397_c2465f --label 3888d3 --workdir /github/workspace --rm -e INPUT_SCRIPT -e INPUT_ARGS -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/quarkus-extension-catalog/quarkus-extension-catalog":"/github/workspace" 3888d3:3d5e89bf3b5445b3a1f5add313179397  "https://github.com/quarkusio/quarkus-registry-descriptor/blob/master/index.java" "--trust=https://github.com/quarkusio/quarkus-registry-descriptor/ . ./app/registry.json"
[jbang] https://github.com/quarkusio/quarkus-registry-descriptor/blob/master/index.java is not from a trusted source thus aborting.
If you trust the url to be safe to run are here a few suggestions:
Limited trust:
    jbang --trust=https://github.com/quarkusio/quarkus-registry-descriptor/
Trust all subdomains:
    jbang --trust=*.github.com
Trust all sources (WARNING! disables url protection):
    jbang --trust="*"

For more control edit ~/.jbang/trusted-sources.json

[jbang] Run with --verbose for more details
```

See https://github.com/quarkusio/quarkus-extension-catalog/runs/743885705?check_suite_focus=true for more details (PS: I also noted that the step didn't fail the workflow, maybe open a new ticket for that?)

**Comment by gastaldi** [comment]
It would be nice to have it as a separate parameter, let me see if I can provide a PR fixing it

**Comment by maxandersen** [comment]
ah - the args are not args for jbang but for your script. 

might just work if you put in `script: ` instead ?

**Comment by maxandersen** [comment]
i.e. this might work better:

```
- name: Index Catalog
        uses: jbangdev/jbang-action@v0.28.0
        with:
          script: --trust=https://github.com/quarkusio/quarkus-registry-descriptor/ https://github.com/quarkusio/quarkus-registry-descriptor/blob/master/index.java
          args:  . ./app/registry.json
```

**Comment by gastaldi** [comment]
It almost worked:

```
      - name: Index Catalog
        uses: jbangdev/jbang-action@v0.28.0
        with:
          script: --trust=https://github.com/quarkusio/quarkus-registry-descriptor/ https://github.com/quarkusio/quarkus-registry-descriptor/blob/master/index.java
          args: . ./app/registry.json
```

Gives 

```java
[jbang] Adding [https://github.com/quarkusio/quarkus-registry-descriptor/ https://github.com/quarkusio/quarkus-registry-descriptor/blob/master/index.java] to /root/.jbang/trusted-sources.json
java.lang.IllegalArgumentException: Could not read script argument . ./app/registry.json
	at dk.xam.jbang.Main.prepareScript(Main.java:939)
	at dk.xam.jbang.Main.doCall(Main.java:312)
	at dk.xam.jbang.Main.call(Main.java:365)
	at dk.xam.jbang.Main.call(Main.java:75)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1783)
	at picocli.CommandLine.access$900(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2150)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2144)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2108)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:1975)
	at picocli.CommandLine.execute(CommandLine.java:1904)
	at dk.xam.jbang.Main.main(Main.java:190)
```

See https://github.com/quarkusio/quarkus-extension-catalog/runs/743958437?check_suite_focus=true
