### ISSUE TITLE
Aliases doesn't work with jbangdev/jbang-action@v0.35.0

### ISSUE THREAD

**Issue by gastaldi** [jbangdev/jbang-action#7]
I have the following configuration:

```yaml
      - name: Index Catalog
        uses: jbangdev/jbang-action@v0.35.0
        with:
          script: indexcatalog@quarkusio
          args: . ./app/registry.json

```

This is the error I get when Github runs it:

```
Run jbangdev/jbang-action@v0.35.0
  with:
    script: indexcatalog@quarkusio
    args: . ./app/registry.json
mkdir: cannot create directory ‘/github/home/.jbang’: Permission denied
[jbang] java.lang.RuntimeException: Invalid alias name ''
[jbang] Run with --verbose for more details

```
